name: Staging Docker Image CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.1.1
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Publish to Registry
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: webmathmech/front
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     tag_names: true

    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webmathmech/front:${{ github.ref }} # my-image-name:$(date +%s)
    - name: Push the Docker image
      run: docker push webmathmech/front:${{ github.ref }} #docker push --tag my-image-name:$(date +%s)
    # - name: Run the Docker image
    #   run: docker -H ssh://dev@webmathmech.site run --rm my-image-name:$(date +%s)
